### ISSUE TITLE
执行命令  sudo ./cluster-control build  失败了

### ISSUE THREAD

**Issue by demobugcy** [jarlor/hadoop_on_docker#3]
root@ubuntu:/home/q/pak/hadoop_on_docker-main# sudo ./cluster-control build
Hit:1 http://mirrors.aliyun.com/ubuntu focal InRelease
Hit:2 http://mirrors.aliyun.com/ubuntu focal-updates InRelease
Hit:3 http://mirrors.aliyun.com/ubuntu focal-backports InRelease                                          
Hit:4 http://security.ubuntu.com/ubuntu focal-security InRelease                                            
Hit:5 http://mirrors.aliyun.com/docker-ce/linux/ubuntu focal InRelease       
Reading package lists... Done
Building dependency tree       
Reading state information... Done
244 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
apache2 is already the newest version (2.4.41-4ubuntu3.15).
0 upgraded, 0 newly installed, 0 to remove and 244 not upgraded.
Listen 18080 is already in /etc/apache2/ports.conf
Synchronizing state of apache2.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable apache2
ln: failed to create symbolic link '/var/www/html/ambari': File exists
ln: failed to create symbolic link '/var/www/html/HDP': File exists
ln: failed to create symbolic link '/var/www/html/HDP-GPL': File exists
ln: failed to create symbolic link '/var/www/html/HDP-UTILS': File exists
Apache2 has been installed and configured to listen on ports 80 and 18080.
Setting up macvlan for Host
RTNETLINK answers: File exists
RTNETLINK answers: File exists
RTNETLINK answers: File exists
RTNETLINK answers: File exists
ERROR: The Compose file './docker-compose.yml' is invalid because:
networks.hadoop-net.ipam.config value Additional properties are not allowed ('gateway' was unexpected)
Setting up SSH key for hadoop1
Error response from daemon: No such container: hadoop1
Error response from daemon: No such container: hadoop1
Error response from daemon: No such container: hadoop1
cat: ./id_rsa.pub: No such file or directory
rm: cannot remove './id_rsa.pub': No such file or directory
Setting up SSH key for hadoop2
Error response from daemon: No such container: hadoop2
Error response from daemon: No such container: hadoop2
Error response from daemon: No such container: hadoop2
cat: ./id_rsa.pub: No such file or directory
rm: cannot remove './id_rsa.pub': No such file or directory
Setting up SSH key for hadoop3
Error response from daemon: No such container: hadoop3
Error response from daemon: No such container: hadoop3
Error response from daemon: No such container: hadoop3
cat: ./id_rsa.pub: No such file or directory
rm: cannot remove './id_rsa.pub': No such file or directory
Setting up SSH key for ambari-server
Error response from daemon: No such container: ambari-server
Error response from daemon: No such container: ambari-server
Error response from daemon: No such container: ambari-server
cat: ./id_rsa.pub: No such file or directory
rm: cannot remove './id_rsa.pub': No such file or directory
Successfully copied 1.54kB to hadoop1:/root/.ssh/authorized_keys
Error response from daemon: No such container: hadoop1
Error response from daemon: No such container: hadoop1
Error response from daemon: No such container: hadoop1
Error response from daemon: No such container: hadoop1
Successfully copied 1.54kB to hadoop2:/root/.ssh/authorized_keys
Error response from daemon: No such container: hadoop2
Error response from daemon: No such container: hadoop2
Error response from daemon: No such container: hadoop2
Error response from daemon: No such container: hadoop2
Successfully copied 1.54kB to hadoop3:/root/.ssh/authorized_keys
Error response from daemon: No such container: hadoop3
Error response from daemon: No such container: hadoop3
Error response from daemon: No such container: hadoop3
Error response from daemon: No such container: hadoop3
Successfully copied 1.54kB to ambari-server:/root/.ssh/authorized_keys
Error response from daemon: No such container: ambari-server
Error response from daemon: No such container: ambari-server
Error response from daemon: No such container: ambari-server
Error response from daemon: No such container: ambari-server
Error response from daemon: No such container: ambari-server
SSH setup completed for all containers.
Setting up cluster environment variables
Error response from daemon: No such container: ambari-server
Error response from daemon: No such container: hadoop1
Error response from daemon: No such container: hadoop1
Error response from daemon: No such container: ambari-server
Error response from daemon: No such container: hadoop2
Error response from daemon: No such container: hadoop2
Error response from daemon: No such container: ambari-server
Error response from daemon: No such container: hadoop3
Error response from daemon: No such container: hadoop3
Cluster environment variables set up on all containers.
Installing Java on hadoop1
no such directory
Error response from daemon: No such container: hadoop1
Error response from daemon: No such container: hadoop1
Error response from daemon: No such container: hadoop1
Error response from daemon: No such container: hadoop1
Error response from daemon: No such container: hadoop1
Java installed on hadoop1
Installing Java on hadoop2
no such directory
Error response from daemon: No such container: hadoop2
Error response from daemon: No such container: hadoop2
Error response from daemon: No such container: hadoop2
Error response from daemon: No such container: hadoop2
Error response from daemon: No such container: hadoop2
Java installed on hadoop2
Installing Java on hadoop3
no such directory
Error response from daemon: No such container: hadoop3
Error response from daemon: No such container: hadoop3
Error response from daemon: No such container: hadoop3
Error response from daemon: No such container: hadoop3
Error response from daemon: No such container: hadoop3
Java installed on hadoop3
Java installation completed on all containers.
Error response from daemon: No such container: ambari-server

**Comment by jarlor** [comment]
从你提供的报错上看有一段是:
``` bash
ERROR: The Compose file './docker-compose.yml' is invalid because:
networks.hadoop-net.ipam.config value Additional properties are not allowed ('gateway' was unexpected)
```
我想你可能需要仔细检查下你的配置文件`cluster_config`其中有没有拼写错误，或者是无效配置的地方。
